name: silta
recipe: drupal9

config:
  php: '7.4'
  via: nginx
  webroot: web
  database: mariadb:10.3
  xdebug: off
  config:
    php: .lando/php.ini

tooling:
  grumphp:
    description: Runs grumphp commands
    cmd:
      - appserver: ./vendor/bin/grumphp
  npm:
    description: Runs npm commands
    service: node
  phpunit:
    description: Runs PHPUnit commands
    cmd:
      - appserver: "php /app/vendor/bin/phpunit -c /app/phpunit.xml"
  xdebug:
    description: Loads Xdebug in the selected mode
    cmd:
      - appserver: /app/.lando/xdebug.sh
    user: root

services:
  appserver:
    build:
      - composer install
    run_as_root:
      - /app/.lando/phpunit.sh
    overrides:
      environment:
        HASH_SALT: notsosecurehash
        ENVIRONMENT_NAME: local
        DB_NAME_DRUPAL: drupal9
        DB_USER_DRUPAL: drupal9
        DB_PASS_DRUPAL: drupal9
        DB_HOST_DRUPAL: database
        # Support debugging with XDEBUG 3.
        XDEBUG_MODE:
        # Support debugging Drush with XDEBUG 3.
        PHP_IDE_CONFIG: "serverName=appserver"
        # PHPUnit settings. @see: .lando/phpunit.sh
        MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless"]}}, "http://chrome:9515"]'
  chrome:
    type: compose
    services:
      image: drupalci/webdriver-chromedriver:production
      command: chromedriver --log-path=/tmp/chromedriver.log --verbose --whitelisted-ips=
  # elasticsearch:
  #   type: compose
  #   services:
  #     image: bitnami/elasticsearch:7
  #     command: /opt/bitnami/scripts/elasticsearch/entrypoint.sh /opt/bitnami/scripts/elasticsearch/run.sh
  #     ports:
  #       - "9200:9200"
  #       - "9300:9300"
  #     volumes:
  #       - ./.lando/elasticsearch.yml:/opt/bitnami/elasticsearch/config/elasticsearch.yml
  #       - elasticsearch_data:/bitnami/elasticsearch/data
  #   volumes:
  #     elasticsearch_data:
  #   overrides:
  #     environment:
  #       ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  #       # Install plugins.
  #       ELASTICSEARCH_PLUGINS: "analysis-icu"
  # kibana:
  #   type: compose
  #   services:
  #     image: bitnami/kibana:7
  #     ports:
  #       - "5601:5601"
  #     depends_on:
  #       - elasticsearch
  #     command: /app-entrypoint.sh /run.sh
  #   overrides:
  #     environment:
  #       KIBANA_ELASTICSEARCH_URL: "http://elasticsearch:9200"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  node:
    type: node
    build:
      - npm install

proxy:
  mailhog:
    - mail-silta.lndo.site

events:
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cache:rebuild -y && drush @local user:login

env_file:
  - .lando/.env

# Tested with Lando version
version: v3.0.23
